import urllib.request as req
try:
    import requests
    except ImportError:
        requests = None

        class Ingredient:
            def __init__(self, quantity, unit, name):
                    self.quantity = quantity
                            self.unit = unit
                                    self.name = name


                                    def get_html(url: str) -> str:
                                        headers = {
                                                "User-Agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36",
                                                        "Accept-Language": "en-US,en;q=0.9",
                                                                "Accept": "text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,*/*;q=0.8",
                                                                        "Referer": url,
                                                                                "Connection": "keep-alive",
                                                                                        "DNT": "1",
                                                                                            }
                                                                                                if requests:
                                                                                                        resp = requests.get(url, headers=headers, timeout=10)
                                                                                                                resp.raise_for_status()
                                                                                                                        return resp.text
                                                                                                                            else:
                                                                                                                                    request = req.Request(url, headers=headers)
                                                                                                                                            with req.urlopen(request) as response:
                                                                                                                                                        data = response.read()
                                                                                                                                                                    return data.decode("utf-8")


                                                                                                                                                                    def get_info(html: str, url: str = None):
                                                                                                                                                                        """
                                                                                                                                                                            Parse ingredient triples from html and return list of Ingredient.
                                                                                                                                                                                Dispatches to a site-specific parser if known, else tries all parsers.
                                                                                                                                                                                    """
                                                                                                                                                                                        def parse_site1(html):
                                                                                                                                                                                                # Original parser for site with data-ingredient-* attributes
                                                                                                                                                                                                        items = []
                                                                                                                                                                                                                current_index = 0
                                                                                                                                                                                                                        while True:
                                                                                                                                                                                                                                    start_q = html.find('data-ingredient-quantity="true">', current_index)
                                                                                                                                                                                                                                                if start_q == -1:
                                                                                                                                                                                                                                                                break
                                                                                                                                                                                                                                                                            start_q += len('data-ingredient-quantity="true">')
                                                                                                                                                                                                                                                                                        end_q = html.find('</span>', start_q)
                                                                                                                                                                                                                                                                                                    if end_q == -1:
                                                                                                                                                                                                                                                                                                                    break
                                                                                                                                                                                                                                                                                                                                quantity = html[start_q:end_q].strip()

                                                                                                                                                                                                                                                                                                                                            start_u = html.find('data-ingredient-unit="true">', end_q)
                                                                                                                                                                                                                                                                                                                                                        if start_u == -1:
                                                                                                                                                                                                                                                                                                                                                                        break
                                                                                                                                                                                                                                                                                                                                                                                    start_u += len('data-ingredient-unit="true">')
                                                                                                                                                                                                                                                                                                                                                                                                end_u = html.find('</span>', start_u)
                                                                                                                                                                                                                                                                                                                                                                                                            if end_u == -1:
                                                                                                                                                                                                                                                                                                                                                                                                                            break
                                                                                                                                                                                                                                                                                                                                                                                                                                        unit = html[start_u:end_u].strip()

                                                                                                                                                                                                                                                                                                                                                                                                                                                    start_n = html.find('data-ingredient-name="true">', end_u)
                                                                                                                                                                                                                                                                                                                                                                                                                                                                if start_n == -1:
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                break
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            start_n += len('data-ingredient-name="true">')
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        end_n = html.find('</span>', start_n)
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    if end_n == -1:
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    break
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                name = html[start_n:end_n].strip()

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            items.append(Ingredient(quantity, unit, name))
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        current_index = end_n
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                return items

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    def parse_site2(html):
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            # Example: Allrecipes.com style (li class="ingredients-item")
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    import re
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            items = []
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    pattern = re.compile(r'<li[^>]*class="[^\"]*ingredients-item[^\"]*"[^>]*>(.*?)</li>', re.DOTALL)
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            for match in pattern.finditer(html):
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        li = match.group(1)
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    # Try to extract quantity, unit, name from text
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                text = re.sub(r'<[^>]+>', '', li).strip()
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            # Naive split: e.g. "1 cup sugar" -> [1, cup, sugar]
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        parts = text.split()
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    if len(parts) >= 3:
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    quantity, unit = parts[0], parts[1]
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    name = ' '.join(parts[2:])
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                elif len(parts) == 2:
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                quantity, unit = parts[0], ''
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                name = parts[1]
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            elif len(parts) == 1:
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            quantity, unit, name = '', '', parts[0]
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        else:
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        continue
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    items.append(Ingredient(quantity, unit, name))
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            return items


    def parse_site3(html):
        # tastesbetterfromscratch.com style (li class="wprm-recipe-ingredient")
        import re
        items = []
        pattern = re.compile(r'<li[^>]*class="[^"]*wprm-recipe-ingredient[^"]*"[^>]*>(.*?)</li>', re.DOTALL)
        for match in pattern.finditer(html):
            li = match.group(1)
            # Extract amount, unit, name
            amount = ''
            unit = ''
            name = ''
            m_amount = re.search(r'<span[^>]*class="[^"]*wprm-recipe-ingredient-amount[^"]*"[^>]*>(.*?)</span>', li)
            if m_amount:
                amount = m_amount.group(1).strip()
            m_unit = re.search(r'<span[^>]*class="[^"]*wprm-recipe-ingredient-unit[^"]*"[^>]*>(.*?)</span>', li)
            if m_unit:
                unit = m_unit.group(1).strip()
            m_name = re.search(r'<span[^>]*class="[^"]*wprm-recipe-ingredient-name[^"]*"[^>]*>(.*?)</span>', li)
            if m_name:
                name = m_name.group(1).strip()
            if name:
                items.append(Ingredient(amount, unit, name))
        return items

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    # Dispatch based on URL or HTML signature
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        if url:
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                if 'allrecipes.' in url:
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            items = parse_site2(html)
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        if items:
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        return items
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                if 'tastesbetterfromscratch.' in url:
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            items = parse_site3(html)
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        if items:
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        return items
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                # Add more site checks here

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    # Try all known parsers, return first with results
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        for parser in [parse_site1, parse_site2, parse_site3]:
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                items = parser(html)
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        if items:
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    return items
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    